image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      mkdir .vscode; echo '{"typescript.validate.enable": false}' > .vscode/settings.json
      npm install
    command: npm start
ports:
  # preview
  - port: 8000
    onOpen: open-preview
  # live-reload: Broken because of bad automatic configuration of live-reload plugin
  # See: https://github.com/schickling/gulp-webserver/pull/126
  # Once it's released, we will be able to set livereload config with custom `src` target
  # to the right URL (found with `gp url <port>`)
  - port: 35729
    onOpen: ignore

vscode:
  extensions:
    - spmeesseman.vscode-taskexplorer@1.26.3:jWv97Y3IpQAHv2qzpsQ5+A==
    - samverschueren.linter-xo@2.3.3:OupKwcpWq2n4ERC1cVBpGQ==
    - maty.vscode-mocha-sidebar@0.22.2:36b0Ya+VBWm0l513u6bBNQ==
